// Code generated by "stringer -type=CanonicalType"; DO NOT EDIT.

package inspectdata

import "strconv"

const _CanonicalType_name = "UnknownUUIDv4IPv4IPv6EmailCountryCode2CountryCode3LanguageCode2LanguageCode3USPostalCodeSSNUSDLatLongDateCCYYMMDDPANAmexPANVisaPANMCPANDiscoverPANDinersPANJCB"

var _CanonicalType_index = [...]uint8{0, 7, 13, 17, 21, 26, 38, 50, 63, 76, 88, 91, 94, 101, 113, 120, 127, 132, 143, 152, 158}

func (i CanonicalType) String() string {
	if i < 0 || i >= CanonicalType(len(_CanonicalType_index)-1) {
		return "CanonicalType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CanonicalType_name[_CanonicalType_index[i]:_CanonicalType_index[i+1]]
}
